import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CustomThemeProvider } from "@/providers/theme-providers";
import { Header } from "@/components/Custom/Header";
import { Footer } from "@/components/Custom/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <CustomThemeProvider
          attribute={'class'}
          defaultTheme='system'
          enableSystem
        >
          <Header />
          {children}
          <Footer />
        </CustomThemeProvider>
      </body>
    </html>
  );
}
